# Generated by Django 5.2.6 on 2025-12-13 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0002_delete_about_delete_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
                ('link', models.URLField()),
            ],
        ),
    ]
